#ifndef SHRIMPP_DEFINES_HPP
#define SHRIMPP_DEFINES_HPP

#define DEBUG_TESTFILE
//#define DEBUG_TRACE_EXECUTION
//#define DEBUG_PRINT_CODE
//#define DEBUG_STRESS_GC
//#define DEBUG_LOG_GC

#endif //SHRIMPP_DEFINES_HPP
